export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_RESULTS_PENDING = 'REQUEST_RESULTS_PENDING';
export const REQUEST_RESULTS_SUCCESS = 'REQUEST_RESULTS_SUCCESS';
export const REQUEST_RESULTS_FAILED = 'REQUEST_RESULTS_FAILED';

export const GET_RECIPE_ID = 'GET_RECIPE_ID';

export const REQUEST_RECIPE_PENDING = 'REQUEST_RECIPES_PENDING';
export const REQUEST_RECIPE_SUCCESS = 'REQUEST_RECIPES_SUCCESS';
export const REQUEST_RECIPE_FAILED = 'REQUEST_RECIPES_FAILED';